language: bash

sudo: required

env:
  - TRAVIS_BASH_VERSION="4.0"

before_install:
  - ./tests/integ-tests/install-bash.sh "$TRAVIS_BASH_VERSION"

install:
  - PATH=$PWD/bin:$PATH
  - junest setup
  - junest -- echo "Installing JuNest (\$(uname -m))"
  - JUNEST_HOME=~/.junest-arm junest setup --arch arm
  - JUNEST_HOME=~/.junest-arm junest proot --fakeroot -- echo "Installing JuNest (\$(uname -m))"

script:
  - bash --version
  - bash ./tests/checkstyle/checkstyle.sh
  - bash ./tests/unit-tests/unit-tests.sh

  # Multiple tests against different execution modes:
  - junest proot --fakeroot -- ${PWD}/lib/checks/check.sh --skip-aur-tests
  - junest proot -- ${PWD}/lib/checks/check.sh --skip-aur-tests --use-sudo
  - junest ns --fakeroot -- ${PWD}/lib/checks/check.sh --skip-aur-tests
  - junest ns -- ${PWD}/lib/checks/check.sh --use-sudo
  - sudo -E ${PWD}/bin/junest groot -- ${PWD}/lib/checks/check.sh --run-root-tests --skip-aur-tests
  - yes | junest setup --delete

  - JUNEST_HOME=~/.junest-arm junest proot --fakeroot -- ${PWD}/lib/checks/check.sh --skip-aur-tests
  - yes | JUNEST_HOME=~/.junest-arm junest setup --delete
