language: bash

sudo: required

env:
  - TRAVIS_BASH_VERSION="4.0"

before_install:
  - ./tests/integ-tests/install-bash.sh "$TRAVIS_BASH_VERSION"

install:
  - PATH=$PWD/bin:$PATH
  - junest -- echo "Installing JuNest (\$(uname -m))"
  - JUNEST_HOME=~/.junest-arm junest -a arm -- echo "Installing JuNest (\$(uname -m))"

script:
  - bash --version
  - bash ./tests/checkstyle/checkstyle.sh
  - bash ./tests/unit-tests/unit-tests.sh

  # Multiple tests against different execution modes:
  # TODO AUR installation check is currently disabled
  - junest -f -- ${PWD}/lib/checks/check.sh --skip-aur-tests
  - junest -u -- ${PWD}/lib/checks/check.sh --skip-aur-tests
  - sudo -E ${PWD}/bin/junest -g -- ${PWD}/lib/checks/check.sh --skip-aur-tests
  - yes | junest --delete

  - JUNEST_HOME=~/.junest-arm junest -f -- ./lib/checks/check.sh --skip-aur-tests
  - yes | JUNEST_HOME=~/.junest-arm junest --delete
