language: bash

sudo: required

env:
  - TRAVIS_BASH_VERSION="4.0"

before_install:
  - ./tests/integ-tests/install-bash.sh "$TRAVIS_BASH_VERSION"

install:
  - PATH=$PWD/bin:$PATH
  - junest setup
  - junest -- echo "Installing JuNest (\$(uname -m))"
  - JUNEST_HOME=~/.junest-arm junest setup --arch arm
  - JUNEST_HOME=~/.junest-arm junest proot --fakeroot -- echo "Installing JuNest (\$(uname -m))"

script:
  - bash --version
  - bash ./tests/checkstyle/checkstyle.sh
  - bash ./tests/unit-tests/unit-tests.sh

  - export JUNEST_HOME=~/.junest
  - ${PWD}/lib/checks/check_all.sh
  - yes | junest setup --delete

  - export JUNEST_HOME=~/.junest-arm
  - ${PWD}/lib/checks/check_all.sh
  - yes | junest setup --delete
